<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\eCatalogo.Core\eCatalogo.Core.csproj" />
    <ProjectReference Include="..\eCatalogo.UseCases\eCatalogo.UseCases.csproj" />
  </ItemGroup>

</Project>
